### ISSUE TITLE
Geographical location data

### ISSUE THREAD

**Issue by mreza-sharifi** [mostafa-kheibary/tehran-metro-data#1]
Containing geo-location data makes it easy to draw on a map.

**Comment by mostafa-kheibary** [comment]
i will definitely add the geo data soon, probably within two weeks from now. However, if anyone wants to work on it sooner, they are welcome to add this data to the collection and commit it. I would be thankful for their contribution.

**Comment by mostafa-kheibary** [comment]
Hi,
The Geo-location propery added to the data.
